# Generated by Django 5.0.6 on 2024-06-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_activity_user_alter_category_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="category",
        ),
        migrations.AddField(
            model_name="activity",
            name="categories",
            field=models.ManyToManyField(related_name="activities", to="core.category"),
        ),
    ]
