# Generated by Django 5.0.6 on 2024-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_activity_category_activity_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="duration",
            field=models.IntegerField(help_text="Duration in minutes."),
        ),
    ]
